version: '3.1'

services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  rabbitmq:
      image: rabbitmq:management-alpine
      container_name: rabbitmq
      ports:
        - '5672:5672'
    
  gateway:
      build: 
        context: ./gateway
        dockerfile: Dockerfile
      container_name: gateway
      ports:
        - '3000:3000'
      depends_on:
        - rabbitmq
      restart: unless-stopped
      env_file:
        - ./gateway/.env
      volumes:
        - ./gateway:/app/
        - /app/node_modules
    
  auth:
      build: 
        context: ./authService
        dockerfile: Dockerfile
      container_name: authService
      ports:
        - '3001:3001'
        - '5555:5555'
      depends_on:
        - db
        - rabbitmq
        - gateway
      restart: unless-stopped
      env_file:
        - ./authService/.env
      volumes:
        - ./authService:/app/
        - /app/node_modules

  products:
      build: 
        context: ./productsService
        dockerfile: Dockerfile
      container_name: productsService
      ports:
        - '3002:3002'
      depends_on:
        - db
        - rabbitmq
        - gateway
      restart: unless-stopped
      env_file:
        - ./productsService/.env
      volumes:
        - ./productsService:/app/
        - /app/node_modules

volumes:
  dbdata: